name: sig
channels:
  - conda-forge
dependencies:
  - python
  - rdkit
  - numpy
  - pandas
  - sympy
  - matplotlib
  - networkx
  - IPython
  - ipython  # DEBUG
  - pip
  - pip:
      - diophantine
